# Generated by Django 4.2.3 on 2023-07-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proect',
            new_name='Project',
        ),
    ]
